---
- name: apache-server
  hosts: local host
  become: yes
  
  tasks:
    - name: ensure apache is latest version installed
      apt:
        name: apache2
        update_cache: yes
        state: present