---
- name: Deploy spring petclinic as Linux Service
  hosts: all
  become: yes
  tasks:
    - name: Update ubuntu packages and install java
      apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
    - name: Create a spring-petclinic directory
      file:
        path: "{{ directory_path }}"
        state: directory
    - name: download spring petclinic
      get_url:
        url: "{{ url_link }}"
        dest: "{{ app_file_name }}"
    - name: Create springbootuser
      user:
        name: "{{ user }}"
        password: spring
        state: present
    - name: Change ownership of jar file
      file:
        path: "{{ app_file_name }}"
        owner: "{{ user }}"
        mode: '500'
        state: file