---
- name: Deploy LAMP stack on ubuntu Service
  hosts: ubuntu
  become: yes
  tasks:
    - name: Update ubuntu packages and apache2
      apt:
        name: apache2
        update_cache: yes
        state: present
    - name: Update ubuntu packages and install php
      apt:
        name:
        - php
        - libapache2-mod-php
        - php-mysql
        - php-cli
        state: present
    - name: Copying text in to info
      copy:
        src: "info.php"
        dest: /var/www/html/info.php
    - name: Make sure a service unit is running
      systemd:
        state: restarted
        name: apache2
    - name: permit traffic in default zone for https service
      firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled